"""
sql_dialect.py — AIBridge SQL Dialect Converter

Converts PostgreSQL SQL (generated by AI) to target database dialect.
This is the foundation for any-to-any database support.

Supported targets:
  postgres    → no conversion needed (passthrough)
  mysql       → MySQL 8.0+ syntax
  sqlserver   → SQL Server 2016+ / Azure SQL syntax
  oracle      → Oracle 12c+ syntax
  snowflake   → Snowflake syntax
  bigquery    → BigQuery standard SQL
  redshift    → Amazon Redshift (PostgreSQL-compatible, minor changes)
  azuresql    → Azure SQL (SQL Server compatible)
  sqlite      → SQLite syntax

v1.0: Initial implementation
"""

import re


# ── Main converter ────────────────────────────────────────────────────────────

def convert_sql(sql: str, target_db: str,
                staging_schema: str = "staging",
                warehouse_schema: str = "warehouse") -> str:
    """
    Convert PostgreSQL SQL to target database dialect.
    Returns converted SQL string.
    """
    if not sql or not sql.strip():
        return sql

    ct = target_db.lower()

    # PostgreSQL and Redshift — no conversion needed
    if ct in ("postgres", "postgresql", "redshift"):
        return sql

    # Apply schema name substitutions first
    converted = sql

    # Route to dialect converter
    if ct == "mysql":
        converted = _to_mysql(converted, staging_schema, warehouse_schema)
    elif ct in ("sqlserver", "mssql", "azuresql"):
        converted = _to_sqlserver(converted, staging_schema, warehouse_schema)
    elif ct == "oracle":
        converted = _to_oracle(converted, staging_schema, warehouse_schema)
    elif ct == "snowflake":
        converted = _to_snowflake(converted, staging_schema, warehouse_schema)
    elif ct == "bigquery":
        converted = _to_bigquery(converted, staging_schema, warehouse_schema)
    elif ct == "sqlite":
        converted = _to_sqlite(converted, staging_schema, warehouse_schema)

    return converted


def convert_scripts(scripts: list, target_db: str,
                    staging_schema: str = "staging",
                    warehouse_schema: str = "warehouse") -> list:
    """Convert a list of SQL scripts to target dialect."""
    if not scripts:
        return scripts

    ct = target_db.lower()
    if ct in ("postgres", "postgresql", "redshift"):
        return scripts  # No conversion needed

    converted = []
    for script in scripts:
        new_script = dict(script)
        original_sql = script.get("sql", "")
        try:
            new_script["sql"] = convert_sql(
                original_sql, target_db, staging_schema, warehouse_schema
            )
            new_script["dialect"] = target_db
        except Exception as e:
            print(f"[SQLDialect] Warning: Could not convert {script.get('name')} to {target_db}: {e}")
            new_script["sql"] = original_sql  # fallback to original
        converted.append(new_script)

    return converted


# ── MySQL converter ───────────────────────────────────────────────────────────

def _to_mysql(sql: str, staging_schema: str, warehouse_schema: str) -> str:
    s = sql

    # SERIAL PRIMARY KEY → INT AUTO_INCREMENT PRIMARY KEY
    s = re.sub(r'\bSERIAL\s+PRIMARY\s+KEY\b',
               'INT AUTO_INCREMENT PRIMARY KEY', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\s+PRIMARY\s+KEY\b',
               'BIGINT AUTO_INCREMENT PRIMARY KEY', s, flags=re.IGNORECASE)

    # SERIAL → INT AUTO_INCREMENT
    s = re.sub(r'\bSERIAL\b', 'INT AUTO_INCREMENT', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\b', 'BIGINT AUTO_INCREMENT', s, flags=re.IGNORECASE)

    # BOOLEAN → TINYINT(1)
    s = re.sub(r'\bBOOLEAN\b', 'TINYINT(1)', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBOOL\b', 'TINYINT(1)', s, flags=re.IGNORECASE)

    # TRUE/FALSE → 1/0
    s = re.sub(r'\bTRUE\b', '1', s, flags=re.IGNORECASE)
    s = re.sub(r'\bFALSE\b', '0', s, flags=re.IGNORECASE)

    # TEXT → LONGTEXT (MySQL TEXT has 65KB limit)
    # Keep VARCHAR as is

    # CURRENT_TIMESTAMP stays the same in MySQL

    # TIMESTAMP DEFAULT CURRENT_TIMESTAMP → same in MySQL 5.7+

    # ON CONFLICT DO NOTHING → INSERT IGNORE
    s = re.sub(
        r'\bON\s+CONFLICT\s+DO\s+NOTHING\b',
        '', s, flags=re.IGNORECASE
    )
    s = re.sub(
        r'\bINSERT\s+INTO\b',
        'INSERT IGNORE INTO', s, flags=re.IGNORECASE
    )

    # ON CONFLICT (col) DO UPDATE SET ... → ON DUPLICATE KEY UPDATE ...
    s = re.sub(
        r'\bON\s+CONFLICT\s*\((\w+)\)\s*DO\s+UPDATE\s+SET\b',
        'ON DUPLICATE KEY UPDATE', s, flags=re.IGNORECASE
    )

    # EXCLUDED.col → VALUES(col)
    s = re.sub(r'\bEXCLUDED\.(\w+)\b', r'VALUES(\1)', s, flags=re.IGNORECASE)

    # CREATE SCHEMA IF NOT EXISTS → CREATE DATABASE IF NOT EXISTS
    s = re.sub(
        r'\bCREATE\s+SCHEMA\s+IF\s+NOT\s+EXISTS\s+"?(\w+)"?\s*;',
        r'CREATE DATABASE IF NOT EXISTS `\1`;', s, flags=re.IGNORECASE
    )
    s = re.sub(
        r'\bCREATE\s+SCHEMA\s+IF\s+NOT\s+EXISTS\s+(\w+)\s*;',
        r'CREATE DATABASE IF NOT EXISTS `\1`;', s, flags=re.IGNORECASE
    )

    # schema.table → `schema`.`table` (MySQL uses backticks)
    s = re.sub(r'"(\w+)"\."(\w+)"', r'`\1`.`\2`', s)
    s = re.sub(rf'\b{re.escape(warehouse_schema)}\.(\w+)\b',
               rf'`{warehouse_schema}`.`\1`', s)
    s = re.sub(rf'\b{re.escape(staging_schema)}\.(\w+)\b',
               rf'`{staging_schema}`.`\1`', s)

    # EXTRACT syntax stays same in MySQL

    # generate_series → not supported, use stored procedure approach
    # For dim_date generation in MySQL we need a different approach
    s = _mysql_date_series(s)

    # CREATE INDEX IF NOT EXISTS → CREATE INDEX (MySQL doesn't support IF NOT EXISTS before 8.0)
    s = re.sub(
        r'\bCREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+(\w+)\s+ON\b',
        r'CREATE INDEX IF NOT EXISTS \1 ON', s, flags=re.IGNORECASE
    )

    # ::DATE, ::INT etc type casts → CAST()
    s = re.sub(r'(\w+)::DATE', r'CAST(\1 AS DATE)', s)
    s = re.sub(r'(\w+)::INT', r'CAST(\1 AS SIGNED)', s)
    s = re.sub(r'(\w+)::INTEGER', r'CAST(\1 AS SIGNED)', s)
    s = re.sub(r"'([^']+)'::DATE", r"CAST('\1' AS DATE)", s)

    # TO_CHAR → DATE_FORMAT
    s = re.sub(r"TO_CHAR\((\w+),\s*'Month'\)",
               r"DATE_FORMAT(\1, '%M')", s, flags=re.IGNORECASE)

    return s


def _mysql_date_series(sql: str) -> str:
    """Replace PostgreSQL generate_series for date dim with MySQL equivalent."""
    if 'generate_series' not in sql.lower():
        return sql

    # Replace the entire generate_series based date insert with MySQL recursive CTE
    pattern = re.compile(
        r"INSERT INTO[^;]+generate_series\('[^']+'::\s*DATE,\s*'[^']+'::\s*DATE,\s*'1 day'::\s*INTERVAL\)[^;]+;",
        re.IGNORECASE | re.DOTALL
    )

    replacement = """INSERT INTO `{warehouse}`.`dim_date` (full_date, year, quarter, month, day, day_of_week, month_name)
WITH RECURSIVE date_series AS (
    SELECT DATE('2020-01-01') AS dt
    UNION ALL
    SELECT DATE_ADD(dt, INTERVAL 1 DAY) FROM date_series WHERE dt < DATE('2030-12-31')
)
SELECT dt, YEAR(dt), QUARTER(dt), MONTH(dt), DAY(dt), DAYOFWEEK(dt), MONTHNAME(dt)
FROM date_series
ON DUPLICATE KEY UPDATE full_date = full_date;"""

    if pattern.search(sql):
        return pattern.sub(replacement, sql)
    return sql


# ── SQL Server converter ──────────────────────────────────────────────────────

def _to_sqlserver(sql: str, staging_schema: str, warehouse_schema: str) -> str:
    s = sql

    # SERIAL PRIMARY KEY → INT IDENTITY(1,1) PRIMARY KEY
    s = re.sub(r'\bSERIAL\s+PRIMARY\s+KEY\b',
               'INT IDENTITY(1,1) PRIMARY KEY', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\s+PRIMARY\s+KEY\b',
               'BIGINT IDENTITY(1,1) PRIMARY KEY', s, flags=re.IGNORECASE)
    s = re.sub(r'\bSERIAL\b', 'INT IDENTITY(1,1)', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\b', 'BIGINT IDENTITY(1,1)', s, flags=re.IGNORECASE)

    # BOOLEAN → BIT
    s = re.sub(r'\bBOOLEAN\b', 'BIT', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBOOL\b', 'BIT', s, flags=re.IGNORECASE)
    s = re.sub(r'\bTRUE\b', '1', s, flags=re.IGNORECASE)
    s = re.sub(r'\bFALSE\b', '0', s, flags=re.IGNORECASE)

    # TIMESTAMP → DATETIME2
    s = re.sub(r'\bTIMESTAMP\b(?!\s+WITH)', 'DATETIME2', s, flags=re.IGNORECASE)

    # CURRENT_TIMESTAMP stays same
    # DEFAULT CURRENT_TIMESTAMP stays same

    # VARCHAR without length → VARCHAR(MAX)
    s = re.sub(r'\bVARCHAR\b(?!\s*\()', 'VARCHAR(255)', s, flags=re.IGNORECASE)

    # CREATE SCHEMA IF NOT EXISTS → IF NOT EXISTS CREATE SCHEMA
    s = re.sub(
        r'\bCREATE\s+SCHEMA\s+IF\s+NOT\s+EXISTS\s+"?(\w+)"?\s*;',
        r"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = '\1') EXEC('CREATE SCHEMA [\1]');",
        s, flags=re.IGNORECASE
    )

    # ON CONFLICT DO NOTHING → no direct equivalent, use MERGE or just remove
    # Simple approach: remove ON CONFLICT and use WHERE NOT EXISTS pattern
    s = re.sub(
        r'\bON\s+CONFLICT\s*\((\w+)\)\s*DO\s+NOTHING\b',
        '', s, flags=re.IGNORECASE
    )
    s = re.sub(
        r'\bON\s+CONFLICT\s+DO\s+NOTHING\b',
        '', s, flags=re.IGNORECASE
    )

    # ON CONFLICT DO UPDATE → MERGE statement
    # This is complex — for now, convert to INSERT IF NOT EXISTS pattern
    s = re.sub(
        r'\bON\s+CONFLICT\s*\(\w+\)\s*DO\s+UPDATE\s+SET[^;]+',
        '', s, flags=re.IGNORECASE | re.DOTALL
    )

    # CREATE TABLE IF NOT EXISTS → IF NOT EXISTS CREATE TABLE
    s = re.sub(
        r'\bCREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+',
        'CREATE TABLE IF NOT EXISTS ', s, flags=re.IGNORECASE
    )
    # SQL Server doesn't support IF NOT EXISTS directly — wrap in check
    s = re.sub(
        r'\bCREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+(\[?\w+\]?\.\[?\w+\]?)',
        r"IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '\1' AND TABLE_NAME = '\1') CREATE TABLE \1",
        s, flags=re.IGNORECASE
    )

    # CREATE INDEX IF NOT EXISTS → no IF NOT EXISTS in SQL Server
    s = re.sub(
        r'\bCREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+(\w+)\s+ON\s+',
        r'CREATE INDEX \1 ON ', s, flags=re.IGNORECASE
    )

    # ::DATE, ::INT type casts → CAST()
    s = re.sub(r"'([^']+)'::DATE", r"CAST('\1' AS DATE)", s)
    s = re.sub(r'\((\w+)\)::DATE', r'CAST(\1 AS DATE)', s)
    s = re.sub(r'(\w+)::INT', r'CAST(\1 AS INT)', s)
    s = re.sub(r'(\w+)::INTEGER', r'CAST(\1 AS INT)', s)

    # EXTRACT → DATEPART
    s = re.sub(r"\bEXTRACT\s*\(\s*YEAR\s+FROM\s+(\w+)\s*\)",
               r'DATEPART(year, \1)', s, flags=re.IGNORECASE)
    s = re.sub(r"\bEXTRACT\s*\(\s*QUARTER\s+FROM\s+(\w+)\s*\)",
               r'DATEPART(quarter, \1)', s, flags=re.IGNORECASE)
    s = re.sub(r"\bEXTRACT\s*\(\s*MONTH\s+FROM\s+(\w+)\s*\)",
               r'DATEPART(month, \1)', s, flags=re.IGNORECASE)
    s = re.sub(r"\bEXTRACT\s*\(\s*DAY\s+FROM\s+(\w+)\s*\)",
               r'DATEPART(day, \1)', s, flags=re.IGNORECASE)
    s = re.sub(r"\bEXTRACT\s*\(\s*DOW\s+FROM\s+(\w+)\s*\)",
               r'DATEPART(weekday, \1)', s, flags=re.IGNORECASE)

    # TO_CHAR → FORMAT
    s = re.sub(r"TO_CHAR\((\w+),\s*'Month'\)",
               r"FORMAT(\1, 'MMMM')", s, flags=re.IGNORECASE)

    # generate_series → SQL Server CTE
    s = _sqlserver_date_series(s, warehouse_schema)

    # schema.table quoting → [schema].[table]
    s = re.sub(r'"(\w+)"\."(\w+)"', r'[\1].[\2]', s)

    return s


def _sqlserver_date_series(sql: str, warehouse_schema: str) -> str:
    if 'generate_series' not in sql.lower():
        return sql

    pattern = re.compile(
        r"INSERT INTO[^;]+generate_series[^;]+;",
        re.IGNORECASE | re.DOTALL
    )

    replacement = f"""INSERT INTO [{warehouse_schema}].[dim_date] (full_date, year, quarter, month, day, day_of_week, month_name)
WITH date_series AS (
    SELECT CAST('2020-01-01' AS DATE) AS dt
    UNION ALL
    SELECT DATEADD(day, 1, dt) FROM date_series WHERE dt < '2030-12-31'
)
SELECT dt, YEAR(dt), DATEPART(quarter,dt), MONTH(dt), DAY(dt), DATEPART(weekday,dt), FORMAT(dt,'MMMM')
FROM date_series
OPTION (MAXRECURSION 5000);"""

    if pattern.search(sql):
        return pattern.sub(replacement, sql)
    return sql


# ── Oracle converter ──────────────────────────────────────────────────────────

def _to_oracle(sql: str, staging_schema: str, warehouse_schema: str) -> str:
    s = sql

    # SERIAL → NUMBER GENERATED ALWAYS AS IDENTITY
    s = re.sub(r'\bSERIAL\s+PRIMARY\s+KEY\b',
               'NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\s+PRIMARY\s+KEY\b',
               'NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY', s, flags=re.IGNORECASE)
    s = re.sub(r'\bSERIAL\b', 'NUMBER GENERATED ALWAYS AS IDENTITY', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\b', 'NUMBER GENERATED ALWAYS AS IDENTITY', s, flags=re.IGNORECASE)

    # INTEGER → NUMBER
    s = re.sub(r'\bINTEGER\b', 'NUMBER', s, flags=re.IGNORECASE)
    s = re.sub(r'\bINT\b(?!\s*\()', 'NUMBER', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGINT\b', 'NUMBER', s, flags=re.IGNORECASE)
    s = re.sub(r'\bSMALLINT\b', 'NUMBER', s, flags=re.IGNORECASE)

    # VARCHAR → VARCHAR2
    s = re.sub(r'\bVARCHAR\b', 'VARCHAR2', s, flags=re.IGNORECASE)

    # BOOLEAN → NUMBER(1)
    s = re.sub(r'\bBOOLEAN\b', 'NUMBER(1)', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBOOL\b', 'NUMBER(1)', s, flags=re.IGNORECASE)
    s = re.sub(r'\bTRUE\b', '1', s, flags=re.IGNORECASE)
    s = re.sub(r'\bFALSE\b', '0', s, flags=re.IGNORECASE)

    # TIMESTAMP DEFAULT CURRENT_TIMESTAMP → TIMESTAMP DEFAULT SYSDATE
    s = re.sub(r'\bCURRENT_TIMESTAMP\b', 'SYSDATE', s, flags=re.IGNORECASE)
    s = re.sub(r'\bCURRENT_DATE\b', 'SYSDATE', s, flags=re.IGNORECASE)

    # CREATE SCHEMA IF NOT EXISTS → Oracle doesn't have schemas like PostgreSQL
    # Oracle uses user/schema equivalently — skip schema creation
    s = re.sub(
        r'\bCREATE\s+SCHEMA\s+IF\s+NOT\s+EXISTS\s+\w+\s*;',
        '-- Schema creation skipped (Oracle uses users as schemas)', s, flags=re.IGNORECASE
    )

    # CREATE TABLE IF NOT EXISTS → Oracle 12.2+ supports IF NOT EXISTS
    # For older: CREATE TABLE (skip if exists via EXCEPTION)
    s = re.sub(
        r'\bCREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+',
        'CREATE TABLE IF NOT EXISTS ', s, flags=re.IGNORECASE
    )

    # CREATE INDEX IF NOT EXISTS → Oracle 21c+
    s = re.sub(
        r'\bCREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+',
        'CREATE INDEX IF NOT EXISTS ', s, flags=re.IGNORECASE
    )

    # ON CONFLICT → Oracle uses MERGE
    # Convert INSERT ... ON CONFLICT DO NOTHING → INSERT ... WHERE NOT EXISTS
    s = re.sub(
        r'\bON\s+CONFLICT\s+DO\s+NOTHING\b',
        '', s, flags=re.IGNORECASE
    )
    s = re.sub(
        r'\bON\s+CONFLICT\s*\(\w+\)\s*DO\s+NOTHING\b',
        '', s, flags=re.IGNORECASE
    )
    s = re.sub(
        r'\bON\s+CONFLICT\s*\(\w+\)\s*DO\s+UPDATE\s+SET[^;]+',
        '', s, flags=re.IGNORECASE | re.DOTALL
    )

    # ::DATE, ::INT casts → Oracle CAST
    s = re.sub(r"'([^']+)'::DATE", r"TO_DATE('\1','YYYY-MM-DD')", s)
    s = re.sub(r'(\w+)::INT', r'CAST(\1 AS NUMBER)', s)
    s = re.sub(r'(\w+)::INTEGER', r'CAST(\1 AS NUMBER)', s)
    s = re.sub(r'(\w+)::DATE', r'CAST(\1 AS DATE)', s)

    # EXTRACT stays same in Oracle

    # TO_CHAR stays same in Oracle (Oracle actually uses same syntax!)

    # generate_series → Oracle CTE
    s = _oracle_date_series(s, warehouse_schema)

    # schema.table quoting
    s = re.sub(r'"(\w+)"\."(\w+)"', r'"\1"."\2"', s)

    return s


def _oracle_date_series(sql: str, warehouse_schema: str) -> str:
    if 'generate_series' not in sql.lower():
        return sql

    pattern = re.compile(
        r"INSERT INTO[^;]+generate_series[^;]+;",
        re.IGNORECASE | re.DOTALL
    )

    replacement = f"""INSERT INTO "{warehouse_schema.upper()}"."DIM_DATE" (full_date, year, quarter, month, day, day_of_week, month_name)
SELECT dt, EXTRACT(YEAR FROM dt), CEIL(EXTRACT(MONTH FROM dt)/3),
       EXTRACT(MONTH FROM dt), EXTRACT(DAY FROM dt),
       TO_NUMBER(TO_CHAR(dt,'D')), TO_CHAR(dt,'Month')
FROM (
    SELECT DATE '2020-01-01' + LEVEL - 1 AS dt
    FROM dual
    CONNECT BY LEVEL <= (DATE '2030-12-31' - DATE '2020-01-01' + 1)
)
WHERE dt NOT IN (SELECT full_date FROM "{warehouse_schema.upper()}"."DIM_DATE")"""

    if pattern.search(sql):
        return pattern.sub(replacement, sql)
    return sql


# ── Snowflake converter ───────────────────────────────────────────────────────

def _to_snowflake(sql: str, staging_schema: str, warehouse_schema: str) -> str:
    s = sql

    # SERIAL → AUTOINCREMENT
    s = re.sub(r'\bSERIAL\s+PRIMARY\s+KEY\b',
               'INT AUTOINCREMENT PRIMARY KEY', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\s+PRIMARY\s+KEY\b',
               'BIGINT AUTOINCREMENT PRIMARY KEY', s, flags=re.IGNORECASE)
    s = re.sub(r'\bSERIAL\b', 'INT AUTOINCREMENT', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\b', 'BIGINT AUTOINCREMENT', s, flags=re.IGNORECASE)

    # BOOLEAN stays same in Snowflake

    # TIMESTAMP stays same

    # ON CONFLICT DO NOTHING → Snowflake doesn't support ON CONFLICT
    # Use INSERT OVERWRITE or just remove
    s = re.sub(
        r'\bON\s+CONFLICT\s+DO\s+NOTHING\b',
        '', s, flags=re.IGNORECASE
    )
    s = re.sub(
        r'\bON\s+CONFLICT\s*\(\w+\)\s*DO\s+NOTHING\b',
        '', s, flags=re.IGNORECASE
    )
    s = re.sub(
        r'\bON\s+CONFLICT\s*\(\w+\)\s*DO\s+UPDATE\s+SET[^;]+',
        '', s, flags=re.IGNORECASE | re.DOTALL
    )

    # CREATE SCHEMA IF NOT EXISTS → same in Snowflake ✓

    # CREATE TABLE IF NOT EXISTS → same in Snowflake ✓

    # CREATE INDEX → Snowflake doesn't use indexes (auto-optimized)
    s = re.sub(
        r'CREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+\w+\s+ON\s+[^;]+;',
        '-- Index creation skipped (Snowflake auto-optimizes)', s, flags=re.IGNORECASE
    )

    # ::DATE, ::INT casts → Snowflake uses :: syntax natively ✓

    # EXTRACT → same in Snowflake ✓

    # TO_CHAR → TO_CHAR works in Snowflake ✓

    # generate_series → Snowflake uses GENERATOR
    s = _snowflake_date_series(s, warehouse_schema)

    return s


def _snowflake_date_series(sql: str, warehouse_schema: str) -> str:
    if 'generate_series' not in sql.lower():
        return sql

    pattern = re.compile(
        r"INSERT INTO[^;]+generate_series[^;]+;",
        re.IGNORECASE | re.DOTALL
    )

    replacement = f"""INSERT INTO {warehouse_schema}.dim_date (full_date, year, quarter, month, day, day_of_week, month_name)
SELECT
    DATEADD(day, SEQ4(), '2020-01-01')::DATE AS dt,
    YEAR(dt), QUARTER(dt), MONTH(dt), DAY(dt), DAYOFWEEK(dt), MONTHNAME(dt)
FROM TABLE(GENERATOR(ROWCOUNT => 4018))
WHERE dt <= '2030-12-31'"""

    if pattern.search(sql):
        return pattern.sub(replacement, sql)
    return sql


# ── BigQuery converter ────────────────────────────────────────────────────────

def _to_bigquery(sql: str, staging_schema: str, warehouse_schema: str) -> str:
    s = sql

    # SERIAL → INT64 (BigQuery uses INT64, no auto-increment — use GENERATE_UUID or row number)
    s = re.sub(r'\bSERIAL\s+PRIMARY\s+KEY\b',
               'INT64', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\s+PRIMARY\s+KEY\b',
               'INT64', s, flags=re.IGNORECASE)
    s = re.sub(r'\bSERIAL\b', 'INT64', s, flags=re.IGNORECASE)

    # INTEGER → INT64
    s = re.sub(r'\bINTEGER\b', 'INT64', s, flags=re.IGNORECASE)
    s = re.sub(r'\bINT\b(?!\s*64)', 'INT64', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGINT\b', 'INT64', s, flags=re.IGNORECASE)

    # NUMERIC → NUMERIC (same)
    # VARCHAR → STRING
    s = re.sub(r'\bVARCHAR\s*\(\d+\)', 'STRING', s, flags=re.IGNORECASE)
    s = re.sub(r'\bVARCHAR\b', 'STRING', s, flags=re.IGNORECASE)

    # BOOLEAN stays same
    # TIMESTAMP → TIMESTAMP (same)
    # DATE → DATE (same)

    # schema.table → `project.dataset.table` format
    # For simplicity: schema.table → `schema`.`table`
    s = re.sub(r'"(\w+)"\."(\w+)"', r'`\1`.`\2`', s)

    # CREATE SCHEMA IF NOT EXISTS → CREATE SCHEMA IF NOT EXISTS (same in BigQuery)

    # CREATE TABLE IF NOT EXISTS → same ✓

    # CREATE INDEX → BigQuery doesn't support traditional indexes
    s = re.sub(
        r'CREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+\w+\s+ON\s+[^;]+;',
        '-- Index creation skipped (BigQuery uses clustering instead)', s, flags=re.IGNORECASE
    )

    # PRIMARY KEY constraint → BigQuery doesn't enforce PK but supports it
    # Remove REFERENCES (FK) constraints — BigQuery doesn't enforce them
    s = re.sub(
        r'\s+REFERENCES\s+[^\s,\)]+\([^\)]+\)',
        '', s, flags=re.IGNORECASE
    )

    # ON CONFLICT → BigQuery uses MERGE
    s = re.sub(
        r'\bON\s+CONFLICT\s+DO\s+NOTHING\b',
        '', s, flags=re.IGNORECASE
    )
    s = re.sub(
        r'\bON\s+CONFLICT\s*\(\w+\)\s*DO\s+NOTHING\b',
        '', s, flags=re.IGNORECASE
    )

    # ::DATE casts → CAST(x AS DATE)
    s = re.sub(r"'([^']+)'::DATE", r"DATE('\1')", s)
    s = re.sub(r'(\w+)::DATE', r'DATE(\1)', s)
    s = re.sub(r'(\w+)::INT', r'CAST(\1 AS INT64)', s)

    # EXTRACT → same in BigQuery ✓

    # TO_CHAR → FORMAT_DATE
    s = re.sub(r"TO_CHAR\((\w+),\s*'Month'\)",
               r"FORMAT_DATE('%B', \1)", s, flags=re.IGNORECASE)

    # generate_series → BigQuery GENERATE_DATE_ARRAY
    s = _bigquery_date_series(s, warehouse_schema)

    return s


def _bigquery_date_series(sql: str, warehouse_schema: str) -> str:
    if 'generate_series' not in sql.lower():
        return sql

    pattern = re.compile(
        r"INSERT INTO[^;]+generate_series[^;]+;",
        re.IGNORECASE | re.DOTALL
    )

    replacement = f"""INSERT INTO `{warehouse_schema}.dim_date` (full_date, year, quarter, month, day, day_of_week, month_name)
SELECT
    dt AS full_date,
    EXTRACT(YEAR FROM dt) AS year,
    EXTRACT(QUARTER FROM dt) AS quarter,
    EXTRACT(MONTH FROM dt) AS month,
    EXTRACT(DAY FROM dt) AS day,
    EXTRACT(DAYOFWEEK FROM dt) AS day_of_week,
    FORMAT_DATE('%B', dt) AS month_name
FROM UNNEST(GENERATE_DATE_ARRAY('2020-01-01', '2030-12-31', INTERVAL 1 DAY)) AS dt"""

    if pattern.search(sql):
        return pattern.sub(replacement, sql)
    return sql


# ── SQLite converter ──────────────────────────────────────────────────────────

def _to_sqlite(sql: str, staging_schema: str, warehouse_schema: str) -> str:
    s = sql

    # SERIAL → INTEGER (SQLite ROWID auto-increment)
    s = re.sub(r'\bSERIAL\s+PRIMARY\s+KEY\b',
               'INTEGER PRIMARY KEY AUTOINCREMENT', s, flags=re.IGNORECASE)
    s = re.sub(r'\bBIGSERIAL\s+PRIMARY\s+KEY\b',
               'INTEGER PRIMARY KEY AUTOINCREMENT', s, flags=re.IGNORECASE)
    s = re.sub(r'\bSERIAL\b', 'INTEGER', s, flags=re.IGNORECASE)

    # BOOLEAN → INTEGER
    s = re.sub(r'\bBOOLEAN\b', 'INTEGER', s, flags=re.IGNORECASE)

    # NUMERIC → REAL
    s = re.sub(r'\bNUMERIC\s*\(\d+,\s*\d+\)', 'REAL', s, flags=re.IGNORECASE)

    # TIMESTAMP → TEXT (SQLite has no native TIMESTAMP)
    s = re.sub(r'\bTIMESTAMP\b', 'TEXT', s, flags=re.IGNORECASE)

    # CREATE SCHEMA → SQLite has no schemas (attach DB instead)
    s = re.sub(
        r'\bCREATE\s+SCHEMA\s+IF\s+NOT\s+EXISTS\s+\w+\s*;',
        '-- SQLite has no schemas', s, flags=re.IGNORECASE
    )

    # Remove schema prefixes (SQLite has no schemas)
    s = re.sub(rf'"{re.escape(warehouse_schema)}"\.', '', s)
    s = re.sub(rf'"{re.escape(staging_schema)}"\.', '', s)
    s = re.sub(rf'\b{re.escape(warehouse_schema)}\.', '', s)
    s = re.sub(rf'\b{re.escape(staging_schema)}\.', '', s)

    # CREATE INDEX IF NOT EXISTS → same ✓

    # ON CONFLICT DO NOTHING → same in SQLite ✓

    # Remove REFERENCES (FK not enforced by default in SQLite)
    # Keep them as documentation

    # ::cast syntax → not supported
    s = re.sub(r"'([^']+)'::DATE", r"date('\1')", s)
    s = re.sub(r'(\w+)::INT', r'CAST(\1 AS INTEGER)', s)
    s = re.sub(r'(\w+)::DATE', r'date(\1)', s)

    # EXTRACT → strftime
    s = re.sub(r"\bEXTRACT\s*\(\s*YEAR\s+FROM\s+(\w+)\s*\)",
               r"CAST(strftime('%Y', \1) AS INTEGER)", s, flags=re.IGNORECASE)
    s = re.sub(r"\bEXTRACT\s*\(\s*MONTH\s+FROM\s+(\w+)\s*\)",
               r"CAST(strftime('%m', \1) AS INTEGER)", s, flags=re.IGNORECASE)
    s = re.sub(r"\bEXTRACT\s*\(\s*DAY\s+FROM\s+(\w+)\s*\)",
               r"CAST(strftime('%d', \1) AS INTEGER)", s, flags=re.IGNORECASE)

    # generate_series → SQLite recursive CTE
    s = _sqlite_date_series(s)

    return s


def _sqlite_date_series(sql: str) -> str:
    if 'generate_series' not in sql.lower():
        return sql

    pattern = re.compile(
        r"INSERT INTO[^;]+generate_series[^;]+;",
        re.IGNORECASE | re.DOTALL
    )

    replacement = """INSERT OR IGNORE INTO dim_date (full_date, year, quarter, month, day, day_of_week, month_name)
WITH RECURSIVE date_series(dt) AS (
    SELECT date('2020-01-01')
    UNION ALL
    SELECT date(dt, '+1 day') FROM date_series WHERE dt < '2030-12-31'
)
SELECT dt,
    CAST(strftime('%Y',dt) AS INTEGER),
    (CAST(strftime('%m',dt) AS INTEGER)+2)/3,
    CAST(strftime('%m',dt) AS INTEGER),
    CAST(strftime('%d',dt) AS INTEGER),
    CAST(strftime('%w',dt) AS INTEGER),
    CASE strftime('%m',dt)
        WHEN '01' THEN 'January' WHEN '02' THEN 'February' WHEN '03' THEN 'March'
        WHEN '04' THEN 'April'   WHEN '05' THEN 'May'      WHEN '06' THEN 'June'
        WHEN '07' THEN 'July'    WHEN '08' THEN 'August'   WHEN '09' THEN 'September'
        WHEN '10' THEN 'October' WHEN '11' THEN 'November' WHEN '12' THEN 'December'
    END
FROM date_series"""

    if pattern.search(sql):
        return pattern.sub(replacement, sql)
    return sql


# ── Utility functions ─────────────────────────────────────────────────────────

def get_supported_targets() -> list:
    return [
        "postgres", "postgresql", "mysql", "sqlserver", "oracle",
        "snowflake", "bigquery", "redshift", "azuresql", "sqlite"
    ]


def get_dialect_info(target_db: str) -> dict:
    info = {
        "postgres":   {"name": "PostgreSQL",      "auto_increment": "SERIAL",           "on_conflict": "ON CONFLICT DO NOTHING", "schemas": True},
        "postgresql": {"name": "PostgreSQL",      "auto_increment": "SERIAL",           "on_conflict": "ON CONFLICT DO NOTHING", "schemas": True},
        "mysql":      {"name": "MySQL",            "auto_increment": "AUTO_INCREMENT",   "on_conflict": "INSERT IGNORE",          "schemas": False},
        "sqlserver":  {"name": "SQL Server",       "auto_increment": "IDENTITY(1,1)",    "on_conflict": "MERGE",                  "schemas": True},
        "oracle":     {"name": "Oracle",           "auto_increment": "GENERATED ALWAYS", "on_conflict": "MERGE INTO",             "schemas": True},
        "snowflake":  {"name": "Snowflake",        "auto_increment": "AUTOINCREMENT",    "on_conflict": "MERGE",                  "schemas": True},
        "bigquery":   {"name": "BigQuery",         "auto_increment": "None (use UUID)",  "on_conflict": "MERGE",                  "schemas": True},
        "redshift":   {"name": "Amazon Redshift",  "auto_increment": "SERIAL",           "on_conflict": "ON CONFLICT DO NOTHING", "schemas": True},
        "azuresql":   {"name": "Azure SQL",        "auto_increment": "IDENTITY(1,1)",    "on_conflict": "MERGE",                  "schemas": True},
        "sqlite":     {"name": "SQLite",           "auto_increment": "AUTOINCREMENT",    "on_conflict": "INSERT OR IGNORE",       "schemas": False},
    }
    return info.get(target_db.lower(), {"name": target_db, "auto_increment": "SERIAL", "on_conflict": "ON CONFLICT", "schemas": True})
